{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/italk_chat\/firebasemanager\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/italk_chat\/firebasemanager\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/init()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@iTalk_Chat@objc(cs)FirebaseManager(im)init","modules":[{"name":"iTalk_Chat"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager"]]},"references":{"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/italk_chat\/firebasemanager\/init()"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager":{"role":"symbol","title":"FirebaseManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseManager"}],"abstract":[{"type":"text","text":"For managing Firebase"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirebaseManager"}],"url":"\/documentation\/italk_chat\/firebasemanager"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat":{"role":"collection","title":"iTalk_Chat","abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager\/title","value":"FirebaseManager"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager\/fragments","value":[{"kind":"identifier","text":"FirebaseManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}