{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/italk_chat\/audioplayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/italk_chat\/audioplayer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/objc(pl)AVAudioPlayerDelegate","doc:\/\/swifbuild94.iTalk-Chat\/7Combine16ObservableObjectP","doc:\/\/swifbuild94.iTalk-Chat\/objc(pl)NSObject","doc:\/\/swifbuild94.iTalk-Chat\/s7CVarArgP","doc:\/\/swifbuild94.iTalk-Chat\/s28CustomDebugStringConvertibleP","doc:\/\/swifbuild94.iTalk-Chat\/s23CustomStringConvertibleP","doc:\/\/swifbuild94.iTalk-Chat\/SQ","doc:\/\/swifbuild94.iTalk-Chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Play Audio"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayer"}],"title":"AudioPlayer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iTalk_Chat@objc(cs)AudioPlayer","modules":[{"name":"iTalk_Chat"}],"navigatorTitle":[{"kind":"identifier","text":"AudioPlayer"}]},"hierarchy":{"paths":[["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/audioPlayer","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/isPlaying","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/objectWillChange"]},{"title":"Instance Methods","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/audioPlayerDidFinishPlaying(_:successfully:)","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/playAudio(_:)","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/stopPlay()"]}],"references":{"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat":{"role":"collection","title":"iTalk_Chat","abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer/isPlaying":{"role":"symbol","title":"isPlaying","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaying"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/isPlaying","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/audioplayer\/isplaying"},"doc://swifbuild94.iTalk-Chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/objc(cs)NSObject"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer/playAudio(_:)":{"role":"symbol","title":"playAudio(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"playAudio"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/playAudio(_:)","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/audioplayer\/playaudio(_:)"},"doc://swifbuild94.iTalk-Chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/objc(pl)NSObject"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer/stopPlay()":{"role":"symbol","title":"stopPlay()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopPlay"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/stopPlay()","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/audioplayer\/stopplay()"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer/audioPlayerDidFinishPlaying(_:successfully:)":{"role":"symbol","title":"audioPlayerDidFinishPlaying(_:successfully:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successfully"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/audioPlayerDidFinishPlaying(_:successfully:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}],"url":"\/documentation\/italk_chat\/audioplayer\/audioplayerdidfinishplaying(_:successfully:)"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer/audioPlayer":{"role":"symbol","title":"audioPlayer","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/audioPlayer","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/audioplayer\/audioplayer"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer/objectWillChange":{"role":"symbol","title":"objectWillChange","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"objectWillChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PassthroughSubject","preciseIdentifier":"s:7Combine18PassthroughSubjectC"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"AudioPlayer","preciseIdentifier":"c:@M@iTalk_Chat@objc(cs)AudioPlayer"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Never","preciseIdentifier":"s:s5NeverO"},{"kind":"text","text":">"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/objectWillChange","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/audioplayer\/objectwillchange"},"doc://swifbuild94.iTalk-Chat/objc(pl)AVAudioPlayerDelegate":{"type":"unresolvable","title":"AVAudioPlayerDelegate","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/objc(pl)AVAudioPlayerDelegate"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer":{"role":"symbol","title":"AudioPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayer"}],"abstract":[{"type":"text","text":"Play Audio"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioPlayer"}],"url":"\/documentation\/italk_chat\/audioplayer"},"doc://swifbuild94.iTalk-Chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/s7CVarArgP"},"doc://swifbuild94.iTalk-Chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/SH"},"doc://swifbuild94.iTalk-Chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/s23CustomStringConvertibleP"},"doc://swifbuild94.iTalk-Chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/SQ"},"doc://swifbuild94.iTalk-Chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/s28CustomDebugStringConvertibleP"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/italk_chat\/audioplayer\/init"},"doc://swifbuild94.iTalk-Chat/7Combine16ObservableObjectP":{"type":"unresolvable","title":"Combine.ObservableObject","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/7Combine16ObservableObjectP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AudioPlayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AudioPlayer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AudioPlayer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/audioPlayerDidFinishPlaying(_:successfully:)","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/init"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer~1audioPlayerDidFinishPlaying(_:successfully:)\/title","value":"audioPlayerDidFinishPlaying:successfully:"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer~1audioPlayerDidFinishPlaying(_:successfully:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}]},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer\/title","value":"AudioPlayer"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer\/fragments","value":[{"kind":"identifier","text":"AudioPlayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}