{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/italk_chat\/firebasemanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/italk_chat\/firebasemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/objc(pl)NSObject","doc:\/\/swifbuild94.iTalk-Chat\/s7CVarArgP","doc:\/\/swifbuild94.iTalk-Chat\/s28CustomDebugStringConvertibleP","doc:\/\/swifbuild94.iTalk-Chat\/s23CustomStringConvertibleP","doc:\/\/swifbuild94.iTalk-Chat\/SQ","doc:\/\/swifbuild94.iTalk-Chat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For managing Firebase"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseManager"}],"title":"FirebaseManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@iTalk_Chat@objc(cs)FirebaseManager","modules":[{"name":"iTalk_Chat"}],"navigatorTitle":[{"kind":"identifier","text":"FirebaseManager"}]},"hierarchy":{"paths":[["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/auth","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/firestore","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/firestoreListener","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/storage"]},{"title":"Instance Methods","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/stopFirestoreListener()"]},{"title":"Type Properties","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/shared"]}],"references":{"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat":{"role":"collection","title":"iTalk_Chat","abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager":{"role":"symbol","title":"FirebaseManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseManager"}],"abstract":[{"type":"text","text":"For managing Firebase"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirebaseManager"}],"url":"\/documentation\/italk_chat\/firebasemanager"},"doc://swifbuild94.iTalk-Chat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/s7CVarArgP"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager/firestore":{"role":"symbol","title":"firestore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"firestore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Firestore","preciseIdentifier":"c:objc(cs)FIRFirestore"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/firestore","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/firebasemanager\/firestore"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FirebaseManager","preciseIdentifier":"c:@M@iTalk_Chat@objc(cs)FirebaseManager"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/shared","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/firebasemanager\/shared"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/init()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/italk_chat\/firebasemanager\/init()"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager/stopFirestoreListener()":{"role":"symbol","title":"stopFirestoreListener()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopFirestoreListener"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/stopFirestoreListener()","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/firebasemanager\/stopfirestorelistener()"},"doc://swifbuild94.iTalk-Chat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/s23CustomStringConvertibleP"},"doc://swifbuild94.iTalk-Chat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/objc(cs)NSObject"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager/auth":{"role":"symbol","title":"auth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"auth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Auth","preciseIdentifier":"c:objc(cs)FIRAuth"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/auth","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/firebasemanager\/auth"},"doc://swifbuild94.iTalk-Chat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/SH"},"doc://swifbuild94.iTalk-Chat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/objc(pl)NSObject"},"doc://swifbuild94.iTalk-Chat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/SQ"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager/storage":{"role":"symbol","title":"storage","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"storage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Storage","preciseIdentifier":"c:objc(cs)FIRStorage"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/storage","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/firebasemanager\/storage"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager/firestoreListener":{"role":"symbol","title":"firestoreListener","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firestoreListener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ListenerRegistration","preciseIdentifier":"c:objc(pl)FIRListenerRegistration"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/firestoreListener","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/firebasemanager\/firestorelistener"},"doc://swifbuild94.iTalk-Chat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/swifbuild94.iTalk-Chat\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"FirebaseManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"FirebaseManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"FirebaseManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager\/init()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager\/title","value":"FirebaseManager"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager\/fragments","value":[{"kind":"identifier","text":"FirebaseManager"}]},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}