{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"player"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successfully"},{"kind":"text","text":" "},{"kind":"internalParam","text":"flag"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/italk_chat\/audioplayer\/audioplayerdidfinishplaying(_:successfully:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/italk_chat\/audioplayer\/audioplayerdidfinishplaying(_:successfully:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/audioPlayerDidFinishPlaying(_:successfully:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successfully"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"audioPlayerDidFinishPlaying(_:successfully:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@iTalk_Chat@objc(cs)AudioPlayer(im)audioPlayerDidFinishPlaying:successfully:","modules":[{"name":"iTalk_Chat"}],"navigatorTitle":[{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}]},"hierarchy":{"paths":[["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer"]]},"references":{"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer":{"role":"symbol","title":"AudioPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayer"}],"abstract":[{"type":"text","text":"Play Audio"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioPlayer"}],"url":"\/documentation\/italk_chat\/audioplayer"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer/audioPlayerDidFinishPlaying(_:successfully:)":{"role":"symbol","title":"audioPlayerDidFinishPlaying(_:successfully:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successfully"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer\/audioPlayerDidFinishPlaying(_:successfully:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}],"url":"\/documentation\/italk_chat\/audioplayer\/audioplayerdidfinishplaying(_:successfully:)"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat":{"role":"collection","title":"iTalk_Chat","abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"audioPlayerDidFinishPlaying:successfully:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"player"},{"kind":"text","text":" "},{"kind":"identifier","text":"successfully:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"flag"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer\/title","value":"AudioPlayer"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer\/fragments","value":[{"kind":"identifier","text":"AudioPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer~1audioPlayerDidFinishPlaying(_:successfully:)\/title","value":"audioPlayerDidFinishPlaying:successfully:"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer~1audioPlayerDidFinishPlaying(_:successfully:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}