{"variants":[{"paths":["\/documentation\/italk_chat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/italk_chat"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat","interfaceLanguage":"swift"},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk-Chat\/Documentation"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Alerts","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioRecorder","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatsVM","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactsVM","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/LogInSignInVM","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/NotificationManager","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/TimerManager"]},{"title":"Structures","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Bubble","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Chat","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatAudioBar","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatTextBar","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatView_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactCell","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactImage","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactsView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactsView_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContentView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContentView_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseConstants","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseDocument","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Grid2","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/GridLayout","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/HistoryCell","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/HistoryView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/HistoryView_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ImagePicker","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ImageZoom","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ImageZoom_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Image_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/InputsButtons","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/LogInView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/LogInView_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/MessageView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/MessagesView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/NotificationsView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/PhotoView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/RecentMessage","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/SettingsView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/SettingsView_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/User","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/iTalkView","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/iTalk_ChatApp","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/iTalk_Previews","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/showAudio","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/showPhoto","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/showText","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/userInfo"]},{"title":"Variables","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/data","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/phonePattern","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/userTest"]},{"title":"Enumerations","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/BubbleColors","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/TypeOfContent"]}],"kind":"symbol","metadata":{"roleHeading":"Application","externalID":"iTalk_Chat","title":"iTalk_Chat","symbolKind":"module","role":"collection","modules":[{"name":"iTalk_Chat"}]},"hierarchy":{"paths":[[]]},"references":{"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseConstants":{"role":"symbol","title":"FirebaseConstants","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseConstants"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseConstants","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirebaseConstants"}],"url":"\/documentation\/italk_chat\/firebaseconstants"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/Alerts":{"role":"symbol","title":"Alerts","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Alerts"}],"abstract":[{"type":"text","text":"Shows Alerts"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Alerts","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Alerts"}],"url":"\/documentation\/italk_chat\/alerts"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseDocument":{"role":"symbol","title":"FirebaseDocument","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseDocument"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirebaseDocument"}],"url":"\/documentation\/italk_chat\/firebasedocument"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ImageZoom":{"role":"symbol","title":"ImageZoom","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageZoom"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ImageZoom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageZoom"}],"url":"\/documentation\/italk_chat\/imagezoom"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ImageZoom_Previews":{"role":"symbol","title":"ImageZoom_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageZoom_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ImageZoom_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageZoom_Previews"}],"url":"\/documentation\/italk_chat\/imagezoom_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/BubbleColors":{"role":"symbol","title":"BubbleColors","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleColors"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/BubbleColors","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BubbleColors"}],"url":"\/documentation\/italk_chat\/bubblecolors"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ChatTextBar":{"role":"symbol","title":"ChatTextBar","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatTextBar"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatTextBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatTextBar"}],"url":"\/documentation\/italk_chat\/chattextbar"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/GridLayout":{"role":"symbol","title":"GridLayout","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"GridLayout"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/GridLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GridLayout"}],"url":"\/documentation\/italk_chat\/gridlayout"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/Image_Previews":{"role":"symbol","title":"Image_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Image_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Image_Previews"}],"url":"\/documentation\/italk_chat\/image_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ChatAudioBar":{"role":"symbol","title":"ChatAudioBar","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAudioBar"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatAudioBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatAudioBar"}],"url":"\/documentation\/italk_chat\/chataudiobar"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/HistoryView_Previews":{"role":"symbol","title":"HistoryView_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HistoryView_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/HistoryView_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HistoryView_Previews"}],"url":"\/documentation\/italk_chat\/historyview_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/userInfo":{"role":"symbol","title":"userInfo","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInfo"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/userInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userInfo"}],"url":"\/documentation\/italk_chat\/userinfo"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/phonePattern":{"role":"symbol","title":"phonePattern","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phonePattern"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/phonePattern","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/phonepattern"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ContactsVM":{"role":"symbol","title":"ContactsVM","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactsVM"}],"abstract":[{"type":"text","text":"To Get All Users and Recent Messages"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactsVM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactsVM"}],"url":"\/documentation\/italk_chat\/contactsvm"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/TimerManager":{"role":"symbol","title":"TimerManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TimerManager"}],"abstract":[{"type":"text","text":"Returns a Timer with second Elapsed"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/TimerManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TimerManager"}],"url":"\/documentation\/italk_chat\/timermanager"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk-Chat/Documentation":{"role":"collectionGroup","title":"``iTalk Chat``","abstract":[{"type":"text","text":"iTalk is a communications app."}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk-Chat\/Documentation","kind":"article","type":"topic","url":"\/documentation\/italk-chat\/documentation"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/InputsButtons":{"role":"symbol","title":"InputsButtons","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InputsButtons"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/InputsButtons","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"InputsButtons"}],"url":"\/documentation\/italk_chat\/inputsbuttons"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ImagePicker":{"role":"symbol","title":"ImagePicker","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePicker"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ImagePicker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePicker"}],"url":"\/documentation\/italk_chat\/imagepicker"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/HistoryView":{"role":"symbol","title":"HistoryView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HistoryView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/HistoryView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HistoryView"}],"url":"\/documentation\/italk_chat\/historyview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/LogInView_Previews":{"role":"symbol","title":"LogInView_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogInView_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/LogInView_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogInView_Previews"}],"url":"\/documentation\/italk_chat\/loginview_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ChatsVM":{"role":"symbol","title":"ChatsVM","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatsVM"}],"abstract":[{"type":"text","text":"Just for inside the ChatView"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatsVM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatsVM"}],"url":"\/documentation\/italk_chat\/chatsvm"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ContactImage":{"role":"symbol","title":"ContactImage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactImage"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactImage"}],"url":"\/documentation\/italk_chat\/contactimage"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/showPhoto":{"role":"symbol","title":"showPhoto","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"showPhoto"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/showPhoto","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showPhoto"}],"url":"\/documentation\/italk_chat\/showphoto"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat":{"role":"collection","title":"iTalk_Chat","abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ChatView_Previews":{"role":"symbol","title":"ChatView_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatView_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatView_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatView_Previews"}],"url":"\/documentation\/italk_chat\/chatview_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/Chat":{"role":"symbol","title":"Chat","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Chat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"url":"\/documentation\/italk_chat\/chat"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioRecorder":{"role":"symbol","title":"AudioRecorder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioRecorder"}],"abstract":[{"type":"text","text":"Record Audio"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioRecorder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioRecorder"}],"url":"\/documentation\/italk_chat\/audiorecorder"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ContactsView":{"role":"symbol","title":"ContactsView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactsView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactsView"}],"url":"\/documentation\/italk_chat\/contactsview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/iTalk_Previews":{"role":"symbol","title":"iTalk_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTalk_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/iTalk_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iTalk_Previews"}],"url":"\/documentation\/italk_chat\/italk_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/RecentMessage":{"role":"symbol","title":"RecentMessage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecentMessage"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/RecentMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecentMessage"}],"url":"\/documentation\/italk_chat\/recentmessage"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ChatView":{"role":"symbol","title":"ChatView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ChatView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatView"}],"url":"\/documentation\/italk_chat\/chatview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/MessageView":{"role":"symbol","title":"MessageView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/MessageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageView"}],"url":"\/documentation\/italk_chat\/messageview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/NotificationsView":{"role":"symbol","title":"NotificationsView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationsView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/NotificationsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotificationsView"}],"url":"\/documentation\/italk_chat\/notificationsview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/showText":{"role":"symbol","title":"showText","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"showText"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/showText","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showText"}],"url":"\/documentation\/italk_chat\/showtext"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/LogInView":{"role":"symbol","title":"LogInView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogInView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/LogInView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogInView"}],"url":"\/documentation\/italk_chat\/loginview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/HistoryCell":{"role":"symbol","title":"HistoryCell","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"HistoryCell"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/HistoryCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HistoryCell"}],"url":"\/documentation\/italk_chat\/historycell"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/iTalk_ChatApp":{"role":"symbol","title":"iTalk_ChatApp","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTalk_ChatApp"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/iTalk_ChatApp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iTalk_ChatApp"}],"url":"\/documentation\/italk_chat\/italk_chatapp"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ContactCell":{"role":"symbol","title":"ContactCell","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactCell"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactCell"}],"url":"\/documentation\/italk_chat\/contactcell"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ContentView_Previews":{"role":"symbol","title":"ContentView_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentView_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContentView_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentView_Previews"}],"url":"\/documentation\/italk_chat\/contentview_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/NotificationManager":{"role":"symbol","title":"NotificationManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NotificationManager"}],"abstract":[{"type":"text","text":"Manage the Notifications"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/NotificationManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NotificationManager"}],"url":"\/documentation\/italk_chat\/notificationmanager"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/Bubble":{"role":"symbol","title":"Bubble","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Bubble"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Bubble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Bubble"}],"url":"\/documentation\/italk_chat\/bubble"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/data":{"role":"symbol","title":"data","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/data","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/data"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ContactsView_Previews":{"role":"symbol","title":"ContactsView_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactsView_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContactsView_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactsView_Previews"}],"url":"\/documentation\/italk_chat\/contactsview_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/SettingsView":{"role":"symbol","title":"SettingsView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/SettingsView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsView"}],"url":"\/documentation\/italk_chat\/settingsview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/PhotoView":{"role":"symbol","title":"PhotoView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/PhotoView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PhotoView"}],"url":"\/documentation\/italk_chat\/photoview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/ContentView":{"role":"symbol","title":"ContentView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/ContentView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentView"}],"url":"\/documentation\/italk_chat\/contentview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/MessagesView":{"role":"symbol","title":"MessagesView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessagesView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/MessagesView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessagesView"}],"url":"\/documentation\/italk_chat\/messagesview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/TypeOfContent":{"role":"symbol","title":"TypeOfContent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TypeOfContent"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/TypeOfContent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TypeOfContent"}],"url":"\/documentation\/italk_chat\/typeofcontent"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/AudioPlayer":{"role":"symbol","title":"AudioPlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioPlayer"}],"abstract":[{"type":"text","text":"Play Audio"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioPlayer"}],"url":"\/documentation\/italk_chat\/audioplayer"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/SettingsView_Previews":{"role":"symbol","title":"SettingsView_Previews","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SettingsView_Previews"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/SettingsView_Previews","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SettingsView_Previews"}],"url":"\/documentation\/italk_chat\/settingsview_previews"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/FirebaseManager":{"role":"symbol","title":"FirebaseManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FirebaseManager"}],"abstract":[{"type":"text","text":"For managing Firebase"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FirebaseManager"}],"url":"\/documentation\/italk_chat\/firebasemanager"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/User":{"role":"symbol","title":"User","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"User"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/User","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"User"}],"url":"\/documentation\/italk_chat\/user"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/showAudio":{"role":"symbol","title":"showAudio","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAudio"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/showAudio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showAudio"}],"url":"\/documentation\/italk_chat\/showaudio"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/userTest":{"role":"symbol","title":"userTest","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"userTest"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"User","preciseIdentifier":"s:10iTalk_Chat4UserV"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/userTest","kind":"symbol","type":"topic","url":"\/documentation\/italk_chat\/usertest"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/Grid2":{"role":"symbol","title":"Grid2","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Grid2"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/Grid2","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Grid2"}],"url":"\/documentation\/italk_chat\/grid2"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/iTalkView":{"role":"symbol","title":"iTalkView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"iTalkView"}],"abstract":[],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/iTalkView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"iTalkView"}],"url":"\/documentation\/italk_chat\/italkview"},"doc://swifbuild94.iTalk-Chat/documentation/iTalk_Chat/LogInSignInVM":{"role":"symbol","title":"LogInSignInVM","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogInSignInVM"}],"abstract":[{"type":"text","text":"For LogIn and SignIn"}],"identifier":"doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/LogInSignInVM","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogInSignInVM"}],"url":"\/documentation\/italk_chat\/loginsigninvm"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk-Chat\/Documentation"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/AudioPlayer","doc:\/\/swifbuild94.iTalk-Chat\/documentation\/iTalk_Chat\/FirebaseManager"]}]},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer\/title","value":"AudioPlayer"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1AudioPlayer\/fragments","value":[{"kind":"identifier","text":"AudioPlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager\/title","value":"FirebaseManager"},{"op":"replace","path":"\/references\/doc:~1~1swifbuild94.iTalk-Chat~1documentation~1iTalk_Chat~1FirebaseManager\/fragments","value":[{"kind":"identifier","text":"FirebaseManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}